### ISSUE TITLE
Create a good README file with compilation instructions

### ISSUE THREAD

**Issue by hitanshu1** [Skylled/Cybertronix#13]
Your application could not be compiled, because its dependencies could not be established.
The following Dart file:
  C:\Users\hitanshu gogoi\Desktop\Cybertronix\lib\cards\document\location.dart
...refers, in an import, to the following library:
  C:\Users\hitanshu gogoi\Desktop\Cybertronix\lib\api.dart
Unfortunately, that library does not appear to exist on your file system.

given problem showing in my screen

**Comment by Skylled** [comment]
Good catch. I need to refactor this tidbit. All `api.dart` contains is a string with an API key for Google Maps. I had intended on explaining that in a Readme.
